#!/usr/bin/env php
<?php
namespace think;

define('APP_PATH', __DIR__ . '/app/');
define('RUNTIME_PATH', __DIR__ . '/runtime/');
define('ROOT_PATH', __DIR__ . '/');

require __DIR__ . '/vendor/autoload.php';

$console = new Console();
$console->run();
